/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mainContractSol from "./MainContract.sol";
export type { mainContractSol };
export type { TokenERC20 } from "./TokenERC20";
export type { TokenERC721 } from "./TokenERC721";
