/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MainContract } from "./MainContract";
export type { TokenERC20 } from "./TokenERC20";
export type { TokenERC721 } from "./TokenERC721";
