/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenERC20 } from "./ITokenERC20";
export type { ITokenERC721 } from "./ITokenERC721";
export type { MainContract } from "./MainContract";
