/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MainContract__factory } from "./MainContract__factory";
export { TokenERC20__factory } from "./TokenERC20__factory";
export { TokenERC721__factory } from "./TokenERC721__factory";
